### ISSUE TITLE
Error Count

### ISSUE THREAD

**Issue by nikue** [informantapp/informant-rails#4]
Great product idea. Small problem with getting started, however. The overall error count doesn't ever seem to match the enumerated errors (please see attached), so I feel like I'm missing something. A little help?
![informant](https://user-images.githubusercontent.com/770102/32987390-8a34c704-ccfb-11e7-945e-0ac36998d44d.png)

**Comment by paulelliott** [comment]
Hey there! Just wanted to let you know that we're continuing to look into why the numbers are that way for your app.

To clarify what you're looking at, the numbers in the graph above show the total number of _form submissions with validation errors_ while the graph below shows _individual attributes causing validation errors_. They aren't supposed to match although the number of errors in the table should be higher than the graph since one or more errors in the table would trigger each failed submission in the graph.

**Comment by nikue** [comment]
Great, thanks Paul. Yes, I would've figured it out if the numbers had been the other way around, but I couldn't square how it shows up at the moment. Cheers!

**Comment by paulelliott** [comment]
Hey there! Just wanted to let you know that we found the bug and were able to fix it in our system. Unfortunately we aren't able to retroactively fix the data but all new validation errors will be correctly reflected in the UI.

We sincerely apologize for the trouble. Thank you for bringing it to our attention!

**Comment by nikue** [comment]
Fantastic, I'll check it out. Cheers!
